<?php
/**
 * @Author Admin
 * @Date   Jul 11, 2022
 */

namespace App\Services;

use YaangVu\Constant\PermissionActionConstant;
use YaangVu\Constant\PermissionConstant;
use YaangVu\Exceptions\ForbiddenException;
use YaangVu\LaravelBase\Services\impl\BaseService;
use YaangVu\SisModel\App\Models\impl\SmsSettingSQL;
use YaangVu\SisModel\App\Traits\RoleAndPermissionTrait;
use Exception;

class SmsSettingService extends BaseService
{
    use RoleAndPermissionTrait;

    function createModel(): void
    {
        $this->model = new SmsSettingSQL();
    }

    public function preAdd(object $request)
    {
        if (!$this->hasPermission(PermissionConstant::smsSetting(PermissionActionConstant::ADD))) {
            throw new ForbiddenException(__('forbidden.forbidden'), new Exception());
        }
        parent::preAdd($request); // TODO: Change the autogenerated stub
    }
}