<?php

namespace App\Services;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use YaangVu\LaravelBase\Services\impl\BaseService;
use YaangVu\SisModel\App\Models\impl\TaskStatusSQL;

class TaskStatusService extends BaseService
{
    /**
     * @Description
     *
     * @Author Admin
     * @Date   Jul 07, 2022
     *
     * @param $id
     *
     * @return Model|Builder|null
     */
    public static function getStatusBySubTaskId($id): Model|Builder|null
    {
        return TaskStatusSQL::query()->where('id', $id)->first();
    }

    function createModel(): void
    {
        $this->model = new TaskStatusSQL();
    }

    public function preAdd(object $request)
    {
        $rules = [
            'name' => 'required',
        ];
        BaseService::doValidate($request, $rules);
        parent::preAdd($request); // TODO: Change the autogenerated stub
    }

}
